name: Deploy Border0 Policy

env:
  BORDER0_ADMIN_TOKEN: ${{ secrets.BORDER0_ADMIN_TOKEN }}

on:
  pull_request:
    types:
      - closed

jobs:
  update-border0-policy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      json_files: ${{ steps.changed_files.outputs.json_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Run update command for each policy file
        run: |
          sudo curl https://download.border0.com/linux_amd64/border0 -o /usr/bin/border0
          sudo chmod +x /usr/bin/border0

      - name: Run update command for each policy file
        run: |
          echo guthub.event.before: ${{ github.event.before }}
          echo guthub.sha: ${{ github.sha }}
          export json_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.json$' | xargs)
          for file in $json_files;
          do
            echo "Processing $file"
            policy_name=$(echo $file | sed 's/\.json$//')
            echo "Policy name: $policy_name"
            border0 policy edit --policy-file=$file --name=$policy_name
          done

      # - name: Run update command for all policy files
      #   run: |
      #     export json_files=$(ls *.json | xargs)
      #     for file in $json_files;
      #     do
      #       echo "Processing $file"
      #       policy_name=$(echo $file | sed 's/\.json$//')
      #       echo "Policy name: $policy_name"
      #       border0 policy edit --policy-file=$file --name=$policy_name
      #     done          
          
          